# 搜索关键词
keyWords:
  - 显示器
  - 面包
  - 小米
  - 米
  - 鞋

# 最低评论数
lowCommentNum: 1
# 最低值率
lowWorthyNum: 6
# 满意商品数量
satisfyNum: 5
# 过滤词
filterWords:
  - "过期"
  - "售罄"

# 定时任务多长执行一次 单位秒 默认 3个小时
tickTime: 3
# 钉钉token
dingdingToken: ""

# 签到时间(默认早上8:30)
cron: "0 10 10 ? * *"
